U zsv_on_macos_fuzz
Signed-off-by: Azeem Sajid <azeem.sajid@gmail.com>

diff --git a/.github/workflows/ci-zsv-on-macos-fuzz.yml b/.github/workflows/ci-zsv-on-macos-fuzz.yml
--- a/.github/workflows/ci-zsv-on-macos-fuzz.yml
+++ b/.github/workflows/ci-zsv-on-macos-fuzz.yml
@@ -40,30 +40,19 @@ jobs:
         mkdir -p afl/optimized
 
         echo "=== Running afl-showmap ==="
-        afl-showmap -e -o /dev/null -- ./afl/fuzz < ../data/test/2tsv-2.csv
-
-        echo "=== Running afl-showmap 2 ==="
-        afl-showmap -e -m none -t 5000 -o /dev/null -Z -- ./afl/fuzz
+        afl-showmap -e -m none -t 5000 -o /dev/null -Z -- ./afl/fuzz < ../data/test/2tsv-2.csv
 
         echo "=== Running ./afl/fuzz with 2tsv-2.csv ==="
         ./afl/fuzz < ../data/test/2tsv-2.csv
 
+        echo "=== Running afl-cmin.bash ==="
+        afl-cmin.bash -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
+
         # echo "=== afl-run ==="
         # make afl-run
 
-        echo "=== Running afl-cmin.bash ==="
-        unset AFL_DISABLE_LLVM_INSTRUMENTATION
-        afl-cmin.bash -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz < ../data/test/2tsv-2.csv && echo "[SUCCESS]" || echo "[FAILURE]"
-
-        echo "=== Running afl-cmin ==="
-        unset AFL_DISABLE_LLVM_INSTRUMENTATION
-        afl-cmin -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz < ../data/test/2tsv-2.csv && echo "[SUCCESS]" || echo "[FAILURE]"
-
-        echo "=== Running afl-cmin.bash 2 ==="
-        afl-cmin.bash -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
-
-        echo "=== Running afl-cmin 2 ==="
-        afl-cmin -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
+        # echo "=== Running afl-cmin ==="
+        # afl-cmin -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
 
         # echo "=== Running afl-fuzz ==="
         # mkdir -p afl/out
