U zsv_on_macos_fuzz
Signed-off-by: Azeem Sajid <azeem.sajid@gmail.com>

diff --git a/.github/workflows/ci-zsv-on-macos-fuzz.yml b/.github/workflows/ci-zsv-on-macos-fuzz.yml
--- a/.github/workflows/ci-zsv-on-macos-fuzz.yml
+++ b/.github/workflows/ci-zsv-on-macos-fuzz.yml
@@ -52,10 +52,10 @@ jobs:
         # make afl-run
 
         echo "=== Running afl-cmin.bash ==="
-        afl-cmin.bash -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
+        AFL_DISABLE_LLVM_INSTRUMENTATION=1 afl-cmin.bash -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
 
         echo "=== Running afl-cmin ==="
-        afl-cmin -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
+        AFL_DISABLE_LLVM_INSTRUMENTATION=1 afl-cmin -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
 
         # echo "=== Running afl-fuzz ==="
         # mkdir -p afl/out
