U zsv_on_macos_fuzz
Signed-off-by: Azeem Sajid <azeem.sajid@gmail.com>

diff --git a/.github/workflows/ci-zsv-on-macos-fuzz.yml b/.github/workflows/ci-zsv-on-macos-fuzz.yml
--- a/.github/workflows/ci-zsv-on-macos-fuzz.yml
+++ b/.github/workflows/ci-zsv-on-macos-fuzz.yml
@@ -37,25 +37,17 @@ jobs:
         cd fuzz
         make afl-build
 
-        mkdir -p afl/optimized
-
-        # echo
-        # echo "=== Running afl-showmap ==="
-        # afl-showmap -e -m none -t 5000 -o /dev/null -Z -- ./afl/fuzz < ../data/test/2tsv-2.csv
-
-        # echo
-        # echo "=== Running ./afl/fuzz with 2tsv-2.csv ==="
-        # ./afl/fuzz < ../data/test/2tsv-2.csv
+        mkdir -p afl/{filtered,optimized}
+        cp ../data/test/2tsv-2.csv afl/filtered/
 
         echo
         echo "=== Running afl-cmin.bash ==="
-        afl-cmin.bash -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
+        afl-cmin.bash -e -i ./afl/filtered/ -o ./afl/optimized -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
+
+        ls -l ./afl/{filtered,optimized}
 
         # echo "=== afl-run ==="
         # make afl-run
-
-        # echo "=== Running afl-cmin ==="
-        # afl-cmin -e -i ../data/test -o ./afl/optimized -T "all" -- ./afl/fuzz && echo "[SUCCESS]" || echo "[FAILURE]"
 
         # echo "=== Running afl-fuzz ==="
         # mkdir -p afl/out
